### ISSUE TITLE
Repository is missing a LICENSE file

### ISSUE THREAD

**Issue by dominiklohmann** [theY4Kman/parsuricata#12]
This project is listed as being licensed under MIT on PyPI and the pyproject.toml in the repository shows this as well:

https://github.com/theY4Kman/parsuricata/blob/35f5536ac2aa112d2d4ce0cb0cef8043e70952b7/pyproject.toml#L6

However, there is no LICENSE or COPYING file in the repository. Would you mind adding one to make the legal situation clearer for use in commercial projects?

**Comment by theY4Kman** [comment]
Oo, thanks for the heads-up; definitely an oversight. I've gone and added the `LICENSE` file and pushed a [0.3.2 release](https://pypi.org/project/parsuricata/0.3.2/) including it in the source distribution.
