### ISSUE TITLE
Multiline rule with newline before first option

### ISSUE THREAD

**Issue by Gladskih** [theY4Kman/parsuricata#4]
Parser fails on line break in the beggining of options section of multiline rules
```
lark.exceptions.UnexpectedCharacters: No terminal defined for '\' at line 135 col 48
cp $HOME_NET any -> $EXTERNAL_NET any ( \
                                        ^
Expecting: {'KEYWORD'}
```

**Comment by theY4Kman** [comment]
mm, sorry for taking a full damn year to get to these, but I pushed a fix for this in [version 0.2.2](https://pypi.org/project/parsuricata/0.2.2/)
